name: turbo_template_scripts
description: CLI scripts for turbo_template project initialization and sync.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.5.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
