name: tool
description: Template initialization script for turbo-template
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
