name: turbo_response_example
description: Turbo Response example project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  turbo_response:

dev_dependencies:
  lints: ^6.0.0
