name: turbo_flutter_template
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cloud_firestore: ^6.1.1
  cloud_functions: ^6.0.5
  connectivity_plus: ^7.0.0
  email_validator: ^3.0.0
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  haptic_feedback: ^0.6.4+3
  hive_ce: ^2.9.0
  mesh_gradient: ^1.3.8
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shadcn_ui: ^0.43.0
  shake_gesture: ^2.0.0
  smooth_sheets: ^0.16.0
  top_snackbar_flutter: ^3.3.0
  turbo_notifiers:
    path: ../../turbo_notifiers
  turbo_response:
    path: ../../turbo_response
  turbo_widgets:
    path: ../../turbo_widgets
  turbolytics:
    path: ../../turbolytics
  turbo_mvvm:
    path: ../../turbo_mvvm
  url_launcher: ^6.3.2
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.3
  mockito: ^5.4.5
  yaml: ^3.1.2
  icons_launcher: ^3.0.1
  intl_utils: ^2.8.13

  firebase_storage_platform_interface: any
  firebase_core_platform_interface: any
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/jpg/
    - assets/lottie/
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-ThinItalic.ttf
          weight: 100
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900

flutter_intl:
  enabled: true
  main_locale: en

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
