name: turbo_firestore_api
description: A clean and efficient approach to dealing with data from Firestore.
version: 0.9.0
resolution: workspace
repository: https://github.com/appboypov/turbo_packages/tree/main/turbo_firestore_api
homepage: https://github.com/appboypov/turbo_packages
issue_tracker: https://github.com/appboypov/turbo_packages/issues

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  turbolytics: ^1.1.0
  turbo_response: ^1.1.0
  turbo_serializable: ^0.3.0
  turbo_notifiers: ^1.1.0

dev_dependencies:
  fake_cloud_firestore: ^4.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0
