name: turbo_firestore_api
description: A clean and efficient approach to dealing with data from Firestore.
version: 0.8.4
resolution: workspace
repository: https://github.com/appboypov/turbo_packages/tree/main/turbo_firestore_api
homepage: https://github.com/appboypov/turbo_packages
issue_tracker: https://github.com/appboypov/turbo_packages/issues

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

  loglytics: ^0.17.0
  turbo_response:
  turbo_serializable:
  informers: ^0.0.5

dev_dependencies:
  fake_cloud_firestore: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.12.0

flutter:
