name: turbo_firestore_api_example
description: Turbo Firestore API example project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  turbolytics:
  turbo_response:
  turbo_notifiers:
  turbo_serializable:
  turbo_firestore_api:
  turbo_mvvm:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
